### ISSUE TITLE
0.77 startet nicht unter ubuntu 18.04

### ISSUE THREAD

**Issue by herrdeh** [jfritz-org/jfritz#19]
JFritz bleibt bei "Initializing Fritz!Box..." hängen, dieses kommt auf dem Terminal:

`$ jfritz
JFritz v0.7.7 Rev. 4f1bb1c (c) 2005-2020 by all members of the JFritz-Team
06.01.20 18:16:12|INFO |main|Main - JFritz v0.7.7 Rev. 4f1bb1c (c) 2005-2020 by all members of the JFritz-Team
06.01.20 18:16:12|INFO |main|Main - JFritz runs on Linux [4.15.0-72-generic]
06.01.20 18:16:12|INFO |main|Main - OS Language: de
06.01.20 18:16:12|INFO |main|Main - OS Country: DE
06.01.20 18:16:12|INFO |main|Main - Java version: 11.0.5 (on amd64)
06.01.20 18:16:12|INFO |main|Main - Working directory: /opt/JFritz/
06.01.20 18:16:12|INFO |main|Main - Data directory: /home/wd/.jfritz/
06.01.20 18:16:13|INFO |main|Main - Selected language: de_DE
06.01.20 18:16:13|INFO |Thread-0|ReverseLookupAsyncThread - finished lookup thread, waiting for new jobs
06.01.20 18:16:18|INFO |main|Main - Detected firmware version: 54.06.06
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at de.bausdorf.avm.tr064.FritzConnection.readTR64(FritzConnection.java:122)
	at de.bausdorf.avm.tr064.FritzConnection.init(FritzConnection.java:111)
	at de.moonflower.jfritz.box.fritzbox.FritzBox.initTR064Connection(FritzBox.java:161)
	at de.moonflower.jfritz.box.fritzbox.FritzBox.init(FritzBox.java:156)
	at de.moonflower.jfritz.JFritz.initFritzBox(JFritz.java:163)
	at de.moonflower.jfritz.Main.initJFritz(Main.java:594)
	at de.moonflower.jfritz.Main.<init>(Main.java:311)
	at de.moonflower.jfritz.Main.main(Main.java:379)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 8 more

`
Kriege dann diese Meldung:
![Bildschirmfoto von 2020-01-06 18-20-33](https://user-images.githubusercontent.com/7152847/71835234-5284c900-30b1-11ea-9142-cbed1d376d34.png)

Es ist egal, ob ich "ja" oder "nein" klicke.

Hab mal .lock im .jfritz-Verzeichnis gelöscht, das hat aber nichts gebracht.
Was mach ich falsch?

System:
ubuntu 18.04
GNOME 3.28.2
12GB RAM
8x Intel xeon

Grüße,
Wolf

**Comment by robotniko** [comment]
Hi, 

ist eine "zu neue" Java Version. Ich habe eine neue Bibliothek eingebunden, die anscheinend mit Java11/13 nicht mehr funktioniert, da in den neueren Java-Versionen Funktionalitäten entfernt wurden.

Ich werde schauen, ob ich am Wochenende Zeit finde, um den Fehler zu beheben. 

Danke für die Meldung

**Comment by herrdeh** [comment]
Hab mal Java 8 aktiviert - das reißt ohne Ende Leistung an sich und
blockiert am Ende komplett den Rechner....

**Comment by Noebian** [comment]
Gleiches (Start)-Problem hier mit Mint 19.2 
0.76 lief problemlos

**Comment by ConnyTheNerd** [comment]
Wollte nur vermelden, dass ich exakt die gleichen Meldungen bekomme wie Threadstarter - arbeite ebenso auf Ubuntu 18.04.

**Comment by robotniko** [comment]
Fixed in 0.7.8
