### ISSUE TITLE
POM missing

### ISSUE THREAD

**Issue by hurzl** [jfritz-org/jfritz#4]
```
$ mvn -amd -U -e clean install
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building jfritz 0.7.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/jfritz/proxy/1.0.2/proxy-1.0.2.pom
[WARNING] The POM for org.jfritz:proxy:jar:1.0.2 is missing, no dependency information available
[WARNING] The POM for org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/jfritz/reverseLookup/1.0.10/reverseLookup-1.0.10.pom
[WARNING] The POM for org.jfritz:reverseLookup:jar:1.0.10 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/jfritz/proxy/1.0.2/proxy-1.0.2.jar
Downloading: https://repo.maven.apache.org/maven2/org/jfritz/reverseLookup/1.0.10/reverseLookup-1.0.10.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.372 s
[INFO] Finished at: 2018-01-07T12:18:30+01:00
[INFO] Final Memory: 12M/302M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jfritz: Could not resolve dependencies for project org.jfritz:jfritz:jar:0.7.6-SNAPSHOT: The following artifacts could not be resolved: org.jfritz:proxy:jar:1.0.2, org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT, org.jfritz:reverseLookup:jar:1.0.10: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project jfritz: Could not resolve dependencies for project org.jfritz:jfritz:jar:0.7.6-SNAPSHOT: The following artifacts could not be resolved: org.jfritz:proxy:jar:1.0.2, org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT, org.jfritz:reverseLookup:jar:1.0.10: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:221)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:246)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.jfritz:jfritz:jar:0.7.6-SNAPSHOT: The following artifacts could not be resolved: org.jfritz:proxy:jar:1.0.2, org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT, org.jfritz:reverseLookup:jar:1.0.10: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:208)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 24 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: org.jfritz:proxy:jar:1.0.2, org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT, org.jfritz:reverseLookup:jar:1.0.10: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:393)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:202)
	... 25 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: The following artifacts could not be resolved: org.jfritz:proxy:jar:1.0.2, org.jfritz:fboxlib:jar:1.0.26-SNAPSHOT, org.jfritz:reverseLookup:jar:1.0.10: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:376)
	... 26 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.jfritz:proxy:jar:1.0.2 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

```
$   mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/share/java/maven
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /usr/local/openjdk8/jre
Default locale: de_DE, platform encoding: UTF-8
OS name: "freebsd", version: "11.1-stable", arch: "amd64", family: "unix"
```

**Comment by robotniko** [comment]
The missing libraries were not uploaded to any maven repository. 
Just download them from https://github.com/jfritz-org and build them yourself with maven to your local maven repository.
